# -*- coding: utf-8 -*-
"""part2_order_system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16dLDturb9qkG9AkcqRmWxtA6obAsVXkZ
"""

# simple implementation using dictionaries and lists
# given data

menu = {
    "Paneer Tikka":   {"category": "Starters",  "price": 180.0, "available": True},
    "Chicken Wings":  {"category": "Starters",  "price": 220.0, "available": False},
    "Veg Soup":       {"category": "Starters",  "price": 120.0, "available": True},
    "Butter Chicken": {"category": "Mains",     "price": 320.0, "available": True},
    "Dal Tadka":      {"category": "Mains",     "price": 180.0, "available": True},
    "Veg Biryani":    {"category": "Mains",     "price": 250.0, "available": True},
    "Garlic Naan":    {"category": "Mains",     "price":  40.0, "available": True},
    "Gulab Jamun":    {"category": "Desserts",  "price":  90.0, "available": True},
    "Rasgulla":       {"category": "Desserts",  "price":  80.0, "available": True},
    "Ice Cream":      {"category": "Desserts",  "price": 110.0, "available": False},
}
# task 1
# exploring menu data

# first getting all categories
cats = []

for item in menu:
    c = menu[item]["category"]
    if c not in cats:
        cats.append(c)

# printing menu category wise
for c in cats:
    print("\n=====", c, "=====")

    for item in menu:
        if menu[item]["category"] == c:

            price = menu[item]["price"]

            # checking if item is available
            if menu[item]["available"] == True:
                status = "Available"
            else:
                status = "Unavailable"

            print(item, "   ₹" + str(price), "  [" + status + "]")


# ---- some basic calculations ----

# total items
total = len(menu)

# counting available items
available = 0
for item in menu:
    if menu[item]["available"] == True:
        available += 1

# finding most expensive item
max_price = 0
max_item = ""

for item in menu:
    if menu[item]["price"] > max_price:
        max_price = menu[item]["price"]
        max_item = item

# items under 150
cheap = []

for item in menu:
    if menu[item]["price"] < 150:
        cheap.append(item)


# ---- printing results ----

print("\nMenu Summary:")

print("Total items:", total)
print("Available items:", available)

print("Most expensive item:", max_item, "-", max_price)

print("\nItems under 150:")
for i in cheap:
    print(i, "-", menu[i]["price"])

# task 2
# cart operations (trying basic approach)

cart = []


# adding item to cart
def add_item(name, qty):

    # checking if item is in menu
    if name not in menu:
        print("item not in menu")
        return

    # checking availability
    if menu[name]["available"] == False:
        print("item not available")
        return

    # checking if already in cart
    already = False

    for x in cart:
        if x["item"] == name:
            x["quantity"] = x["quantity"] + qty
            already = True

    # if not already present
    if already == False:
        cart.append({
            "item": name,
            "quantity": qty,
            "price": menu[name]["price"]
        })

    print("added", name)
    print(cart)


# removing item
def remove_item(name):

    found = False

    for x in cart:
        if x["item"] == name:
            cart.remove(x)
            found = True

    if found == False:
        print("item not found in cart")

    print(cart)


# updating quantity
def update_item(name, qty):

    found = False

    for x in cart:
        if x["item"] == name:
            x["quantity"] = qty
            found = True

    if found == False:
        print("not present in cart")

    print(cart)


# ---- simulation ----

add_item("Paneer Tikka", 2)
add_item("Gulab Jamun", 1)
add_item("Paneer Tikka", 1)

add_item("Mystery Burger", 1)
add_item("Chicken Wings", 1)

remove_item("Gulab Jamun")


# ---- summary ----

print("\nOrder Summary")

subtotal = 0

for x in cart:
    total_price = x["quantity"] * x["price"]
    subtotal = subtotal + total_price

    print(x["item"], "x", x["quantity"], "=", total_price)

print("------------------")

print("Subtotal =", subtotal)

gst = subtotal * 0.05
print("GST =", round(gst, 2))

final = subtotal + gst
print("Total =", round(final, 2))

# given data of inventory for reference

inventory = {
    "Paneer Tikka":   {"stock": 10, "reorder_level": 3},
    "Chicken Wings":  {"stock":  8, "reorder_level": 2},
    "Veg Soup":       {"stock": 15, "reorder_level": 5},
    "Butter Chicken": {"stock": 12, "reorder_level": 4},
    "Dal Tadka":      {"stock": 20, "reorder_level": 5},
    "Veg Biryani":    {"stock":  6, "reorder_level": 3},
    "Garlic Naan":    {"stock": 30, "reorder_level": 10},
    "Gulab Jamun":    {"stock":  5, "reorder_level": 2},
    "Rasgulla":       {"stock":  4, "reorder_level": 3},
    "Ice Cream":      {"stock":  7, "reorder_level": 4},
}
# task 3
# inventory part (checking stock and stuff)

import copy

# taking backup first
inventory_backup = copy.deepcopy(inventory)

# just changing one value to see if copy works
inventory["Paneer Tikka"]["stock"] = 5

print("inventory now:", inventory["Paneer Tikka"])
print("backup still:", inventory_backup["Paneer Tikka"])

# putting back original again
inventory = copy.deepcopy(inventory_backup)


# ---- using cart to reduce stock ----

for i in cart:
    name = i["item"]
    qty = i["quantity"]

    if name in inventory:
        current = inventory[name]["stock"]

        # if enough stock
        if current >= qty:
            inventory[name]["stock"] = current - qty
        else:
            print("stock less for", name)
            inventory[name]["stock"] = 0


# ---- checking which items need reorder ----

print("\ncheck reorder:")

for name in inventory:
    s = inventory[name]["stock"]
    r = inventory[name]["reorder_level"]

    if s <= r:
        print("⚠", name, "low stock:", s, "(limit:", r, ")")


# ---- finalised print ----

print("\nfinal inventory:")
print(inventory)

print("\nbackup inventory:")
print(inventory_backup)

# given data

sales_log = {
    "2025-01-01": [
        {"order_id": 1,  "items": ["Paneer Tikka", "Garlic Naan"], "total": 220.0},
        {"order_id": 2,  "items": ["Gulab Jamun", "Veg Soup"], "total": 210.0},
        {"order_id": 3,  "items": ["Butter Chicken", "Garlic Naan"], "total": 360.0},
    ],
    "2025-01-02": [
        {"order_id": 4,  "items": ["Dal Tadka", "Garlic Naan"], "total": 220.0},
        {"order_id": 5,  "items": ["Veg Biryani", "Gulab Jamun"], "total": 340.0},
    ],
    "2025-01-03": [
        {"order_id": 6,  "items": ["Paneer Tikka", "Rasgulla"], "total": 260.0},
        {"order_id": 7,  "items": ["Butter Chicken", "Veg Biryani"], "total": 570.0},
        {"order_id": 8,  "items": ["Garlic Naan", "Gulab Jamun"], "total": 130.0},
    ],
    "2025-01-04": [
        {"order_id": 9,  "items": ["Dal Tadka", "Garlic Naan", "Rasgulla"], "total": 300.0},
        {"order_id": 10, "items": ["Paneer Tikka", "Gulab Jamun"], "total": 270.0},
    ],
}
# task 4
# checking sales data

print("daily revenue:")

daily = {}

for d in sales_log:
    t = 0

    for o in sales_log[d]:
        t = t + o["total"]

    daily[d] = t
    print(d, t)


# trying to find the best day
best_day = ""
best_val = 0

for d in daily:
    if daily[d] > best_val:
        best_val = daily[d]
        best_day = d

print("\nbest day is:", best_day, best_val)


# trying to find which item is ordered the most
items_count = {}

for d in sales_log:
    for o in sales_log[d]:
        for it in o["items"]:

            if it not in items_count:
                items_count[it] = 1
            else:
                items_count[it] += 1


top_item = ""
top_val = 0

for it in items_count:
    if items_count[it] > top_val:
        top_val = items_count[it]
        top_item = it

print("\nmost ordered item:", top_item, top_val)


# adding new day
sales_log["2025-01-05"] = [
    {"order_id": 11, "items": ["Butter Chicken", "Gulab Jamun", "Garlic Naan"], "total": 490.0},
    {"order_id": 12, "items": ["Paneer Tikka", "Rasgulla"], "total": 260.0},
]


# checking again after adding ther values
print("\nafter adding new day:")

daily = {}

for d in sales_log:
    t = 0
    for o in sales_log[d]:
        t += o["total"]

    daily[d] = t
    print(d, t)


# best day again
best_day = ""
best_val = 0

for d in daily:
    if daily[d] > best_val:
        best_val = daily[d]
        best_day = d

print("\nnew best day:", best_day, best_val)


# printing all orders
print("\nall orders list:")

count = 1

for d in sales_log:
    for o in sales_log[d]:

        items = ", ".join(o["items"])

        print(count, ".", "[" + d + "]",
              "order", o["order_id"],
              "-", o["total"],
              "-", items)

        count += 1